### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by baisui1981** [LittleFall/flink-tidb-rdw#5]
我按照您的例子在测试环境中测试了一下，发现两个问题：

1. 当flink程序启动的时候，我查看了mysql的查询日志，flink会全表扫描主表和字表的数据到内存中
2. 并且启动的时候会对聚合表重新进行 insert replace操作

以上这两个问题，我想在数据量小的时候应该是没有问题的，但是大数据的情况下，做上面这两个操作，性能上，内存开销上肯定是不能接受的。

是否有破解之法？

**Comment by LittleFall** [comment]
抱歉，之前没有看到这条消息。

关于第二个问题，可以设置 cdc 的扫描位点从最新开始，这样就不会全部重新计算一次。

关于第一个问题，我认为这是它在小数据时的独特行为，mysql-cdc 底层还是用的 debezium，可以参考下：
https://github.com/ververica/flink-cdc-connectors/wiki
https://debezium.io/documentation/reference/1.3/connectors/mysql.html
